// Idempotently provision the throwaway E2E test user on the live Supabase project.
//
// Uses the service-role key (from .env.local) to create — or reset the password of
// — a single dedicated account that the Playwright harness logs in as. Real users
// still sign in with Google only; this account exists purely for automated tests.
//
// The password is generated once and persisted to the gitignored e2e/.auth/e2e.env,
// then reused on subsequent runs (so the saved session stays valid). It is never
// printed to stdout.
import { createClient } from "@supabase/supabase-js";
import { mkdirSync, writeFileSync, existsSync, readFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { resolve } from "node:path";
import { loadEnv, ROOT } from "../../e2e/env.mjs";

const { url, serviceKey, email } = loadEnv();

if (!url || !serviceKey) {
  console.error(
    "✗ Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY.\n" +
      "  Run `vercel env pull .env.local` first.",
  );
  process.exit(1);
}

const authDir = resolve(ROOT, "e2e/.auth");
const credsFile = resolve(authDir, "e2e.env");

// Reuse an existing generated password if we already have one; else mint a strong one.
let password = process.env.E2E_PASSWORD;
if (!password && existsSync(credsFile)) {
  const m = readFileSync(credsFile, "utf8").match(/^E2E_PASSWORD=(.*)$/m);
  if (m) password = m[1].trim();
}
if (!password) password = randomBytes(24).toString("base64url");

const admin = createClient(url, serviceKey, {
  auth: { autoRefreshToken: false, persistSession: false },
});

async function findUserByEmail(targetEmail) {
  // listUsers is paginated; scan a few pages defensively.
  for (let page = 1; page <= 10; page++) {
    const { data, error } = await admin.auth.admin.listUsers({ page, perPage: 200 });
    if (error) throw error;
    const hit = data.users.find((u) => u.email?.toLowerCase() === targetEmail.toLowerCase());
    if (hit) return hit;
    if (data.users.length < 200) break;
  }
  return null;
}

const existing = await findUserByEmail(email);

if (existing) {
  const { error } = await admin.auth.admin.updateUserById(existing.id, {
    password,
    email_confirm: true,
  });
  if (error) {
    console.error("✗ Failed to reset E2E user password:", error.message);
    process.exit(1);
  }
  console.log(`✓ E2E user ready (password reset): ${email}`);
} else {
  const { error } = await admin.auth.admin.createUser({
    email,
    password,
    email_confirm: true,
    user_metadata: { e2e: true },
  });
  if (error) {
    console.error("✗ Failed to create E2E user:", error.message);
    process.exit(1);
  }
  console.log(`✓ E2E user created: ${email}`);
}

// Persist creds for the harness (gitignored). Password not echoed to stdout.
mkdirSync(authDir, { recursive: true });
writeFileSync(
  credsFile,
  `# Auto-generated by scripts/e2e/provision-user.mjs — DO NOT COMMIT\nE2E_EMAIL=${email}\nE2E_PASSWORD=${password}\n`,
  { mode: 0o600 },
);
console.log(`✓ Creds written to e2e/.auth/e2e.env (gitignored).`);
