// AUTO-GENERATED by scripts/build-spine-registry.mjs — DO NOT EDIT BY HAND.
// Add an adapter by dropping src/lib/spine/adapters/<id>.ts, then run
// `npm run build:spine`. See docs/app-plans/spine-phase1.md.
import type { SpineAdapter } from "./types";
import { adapter as bills } from "./adapters/bills";
import { adapter as budget } from "./adapters/budget";
import { adapter as carcare } from "./adapters/carcare";
import { adapter as energy } from "./adapters/energy";
import { adapter as goals } from "./adapters/goals";
import { adapter as habits } from "./adapters/habits";
import { adapter as journal } from "./adapters/journal";
import { adapter as keepintouch } from "./adapters/keepintouch";
import { adapter as medication } from "./adapters/medication";
import { adapter as mood } from "./adapters/mood";
import { adapter as plantcare } from "./adapters/plantcare";
import { adapter as sleep } from "./adapters/sleep";
import { adapter as todo } from "./adapters/todo";
import { adapter as water } from "./adapters/water";

export const ADAPTERS: SpineAdapter[] = [bills, budget, carcare, energy, goals, habits, journal, keepintouch, medication, mood, plantcare, sleep, todo, water];
