// AUTO-GENERATED by scripts/build-spine-registry.mjs — DO NOT EDIT BY HAND.
// Add an adapter by dropping src/lib/spine/adapters/<id>.ts, then run
// `npm run build:spine`. See docs/app-plans/spine-phase1.md.
import type { SpineAdapter } from "./types";
import { adapter as bills } from "./adapters/bills";
import { adapter as budget } from "./adapters/budget";
import { adapter as habits } from "./adapters/habits";
import { adapter as journal } from "./adapters/journal";
import { adapter as todo } from "./adapters/todo";
import { adapter as water } from "./adapters/water";

export const ADAPTERS: SpineAdapter[] = [bills, budget, habits, journal, todo, water];
