#!/usr/bin/env node
// Assembles the app catalog from one-JSON-per-app entry files into a typed,
// generated TypeScript module. This is the seam de-confliction from Phase 2 of
// docs/agent-orchestration.md: build agents drop a single entry file in their
// own lane (src/lib/modern/catalog/apps/<id>.json) and NEVER hand-edit a shared
// array, so parallel lanes can't collide on the catalog.
//
// Run via `npm run build:catalog` (also wired into prebuild + pretest).
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const entriesDir = join(root, "src/lib/modern/catalog/apps");
const outFile = join(root, "src/lib/modern/catalog/_generated.ts");

const VALID_UI = ["modern", "tracker", "checklist", "logbook", "goal", "finance", "schedule"];
const TEMPLATE_DISCRIMINATOR = {
  tracker: "trackerType",
  checklist: "listType",
  logbook: "logType",
  goal: "goalType",
  finance: "itemType",
  schedule: "scheduleType",
};

const files = readdirSync(entriesDir).filter((f) => f.endsWith(".json")).sort();
const seen = new Set();
const errors = [];
const entries = [];

for (const file of files) {
  const raw = JSON.parse(readFileSync(join(entriesDir, file), "utf8"));
  const id = file.replace(/\.json$/, "");
  if (raw.id !== id) errors.push(`${file}: "id" ("${raw.id}") must match filename ("${id}")`);
  if (seen.has(id)) errors.push(`${file}: duplicate id "${id}"`);
  seen.add(id);
  for (const k of ["name", "category", "icon", "description", "ui"]) {
    if (!raw[k]) errors.push(`${file}: missing required field "${k}"`);
  }
  if (raw.ui && !VALID_UI.includes(raw.ui)) errors.push(`${file}: unknown ui "${raw.ui}"`);
  const disc = TEMPLATE_DISCRIMINATOR[raw.ui];
  if (disc && !(raw.config && raw.config[disc])) {
    errors.push(`${file}: ui "${raw.ui}" needs config.${disc}`);
  }
  if (typeof raw.order !== "number") errors.push(`${file}: missing numeric "order"`);
  entries.push(raw);
}

if (errors.length) {
  console.error(`build-catalog: ${errors.length} problem(s):\n  ${errors.join("\n  ")}`);
  process.exit(1);
}

// Deterministic display order: by `order`, then id as a stable tiebreak so two
// lanes that happen to pick the same `order` still sort predictably.
entries.sort((a, b) => a.order - b.order || a.id.localeCompare(b.id));

// Strip the assembly-only `order` key; the emitted objects are pure AppEntry.
const lines = entries.map((e) => {
  const entry = { ...e };
  delete entry.order;
  return "  " + JSON.stringify(entry) + ",";
});

const out = `// AUTO-GENERATED by scripts/build-catalog.mjs — DO NOT EDIT BY HAND.
// Add or change an app by editing src/lib/modern/catalog/apps/<id>.json, then
// run \`npm run build:catalog\`. See docs/agent-orchestration.md.
import type { AppEntry } from "./index";

export const APPS: AppEntry[] = [
${lines.join("\n")}
];
`;

writeFileSync(outFile, out);
console.log(`build-catalog: wrote ${entries.length} apps → src/lib/modern/catalog/_generated.ts`);
